### ISSUE TITLE
Input required and not supplied: grafanaText

### ISSUE THREAD

**Issue by asychev** [hexionas/grafana-annotation-action#19]
For update annotation scenario `grafanaText` not used, but still necessary (marked as `required: true`)
Leads to error:

```Error: Input required and not supplied: grafanaText```

```
- name: Update Grafana annotation
   uses: hexionas/grafana-annotation-action@v0
   with:
     grafanaHost: ${{ vars.GRAFANA_HOST }}
      grafanaToken: ${{ secrets.GRAFANA_TOKEN }}
      grafanaAnnotationID: ${{ steps.grafana.outputs.annotation-id }}
```
